### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by oliver-tarrant-tessella** [ukaea/piezo#122]
Trying to run a python job with python version = 3 fails with a message in the logs `+ pyv3='/opt/entrypoint.sh: line 80: python3: command not found'`. It appears that python3 is not installed in our spark image. This should be changed by editing`piezo/Spark/Dockerfile` to ensure that python3  jobs can be run. 

## Acceptance criteria:
- [x] Can run jobs using python 3 
- [x] Python 2 jobs still run

## Test Scenarios in addition to Acceptance criteria scenarios:
- [x] Python 3 job complete successfully
- [x] A user-friendly error message displayed when Py-3 job fails

**Comment by vidhyamanojkumar** [comment]
Language input is case sensitive. 
`"language":"python",` doesn't work, where as `Python` works fine.

**Comment by robert-clegg-tessella** [comment]
The options for `"language"` are clearly documented in the [User guide](https://github.com/ukaea/piezo/wiki/WebAppUserGuide#required-arguments) on the wiki.
