### ISSUE TITLE
Validate arguments passed for a Spark job

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/piezo#17]
Checks the arguments supplied as part of the POST request to the submit-job handler.

## Acceptance Criteria
* If the arguments are all valid, they are then passed to the template builder
* If there are problems with the arguments, then a 400 error is returned together with a useful explanation of all the problems
* Problems include:
  - request for excessive resources (e.g. too many executor nodes)
  - unrecognised options (e.g. unsupported programming language)

## Notes
The [web app user guide](https://github.com/ukaea/piezo/wiki/WebAppUserGuide) describes the input arguments for the submit-job handler.
* Some arguments may have default values, so these can be missing from the arguments
* Some arguments will be language-specific

## Test Scenarios
* Send a valid payload with mandatory only attributes to see 200 status and expected response body
* Send a valid payload with mandatory & all optional attributes to see 200 status and expected response body
* Send a payload with one or more mandatory attributes missing to see 400 status code and a user-friendly error message. 
 **Fail too many details returned when removing required input, e.g. language** Fix verified
* Send a payload with invalid input to the attributes to see 400 status code and a user-friendly error message.
* Check the response time for request is acceptable
* Check the content headers meet the OWASP ASVS

**Comment by oliver-tarrant-tessella** [comment]
Consider making language argument non-case sensitive in the future @robert-clegg-tessella

**Comment by oliver-tarrant-tessella** [comment]
Language should be validated before conditional arguments
