### ISSUE TITLE
Investigate configuration when running in a pod

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/piezo#36]
How do we pass in configuration (e.g. log file location) when running the web app in a pod?

Current approach is to configure as a python file, which is a shortcut and not appropriate for the final deliverable.

**Comment by oliver-tarrant-tessella** [comment]
Work on this has been incorporated into producing a method of deploying the app configurable both to run locally on your system and within a pod. As such this has been combined with #9 and thus I am closing the issue
