### ISSUE TITLE
Deploy services/service monitors

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/piezo#4]
Deploy a service to expose the metrics from a spark driver and executors. The service should expose port 8090 for any pod with the label `piezo-spark-job`. 

Deploy a second service to expose the metrics for spark applications from the spark operator. The service should expose port expose port 10254 for any pod with the label `piezo-spark-operator`. 

Deploy a service monitor to monitor the above services and ensure that this service monitor is included in the services to be monitored by prometheus by ensuring the label matches that specified in the prometheus crd def

### Acceptance criteria
* Running `kubectl get svc --all-namespaces` shows the two services created
* Running `kubectl get servicemonitors --all-namespaces` shows the service monitor created
* When a spark application is run additional spark specific metrics are available via the prometheus dashboard

## Test Scenarios
- Test that running `kubectl get svc --all-namespaces` show the two service (driver and executor/label: piezo-spark-job, piezo-spark-operator) created.
- Test that running `kubectl get servicemonitors --all-namespaces` show the service monitor created
- Check that the Prometheus dashboard is available when spark application is running.
- Check the status of Prometheus dashboard when there is no spark application running.

**Comment by oliver-tarrant-tessella** [comment]
On hold as will be best to incorporate all service deployment into the same script used to deploy the Piezo web app.
