### ISSUE TITLE
Correct validation of driver/executor cores

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/piezo#42]
* Driver cores must be (the string representation of) a float (multiples of 0.1)
* Executor cores must be (the string representation of) an integer

We currently use the same underlying method for both, which is not appropriate.

## Acceptance criteria
The inputs passed to the submit-jobs handler can include "driver_cores" and "executor_cores" (both are optional inputs)
* "driver_cores" can be a multiple of 0.1 (e.g. "0.5" should be accepted) or an integer (e.g. "1" should be accepted) but nothing else (e.g. "0.53" should be rejected)
* "executor_cores" can be an integer (e.g. "3" should be accepted) but nothing else (e.g. "0.5" should be rejected)

Whenever an input is rejected, the message returned to the user should be clear and unambiguous.

## Test Scenarios
* Test that driver_cores with multiple of 0.1 in the payload returns success status.
* Test that driver_cores with 2 decimals in the payload returns 400 status and a user-friendly error message.
* Test that driver_cores with non-numeric value in the payload returns 400 status and a user-friendly error message.
* Test that driver_cores with no input in the payload returns 400 status and a user-friendly error message.
* Test that executor_cores with integer as input in the payload returns success status.
* Test that executor_cores with decimal input in the payload returns 400 status and a user-friendly error message.
* Test that executor_cores with non-numeric value in the payload returns 400 status and a user-friendly error message.
* Test that executor_cores with no input in the payload returns 400 status and a user-friendly error message.
* Test for min and max boundary limits on driver_cores
* Test for min and max boundary limits on executor_cores
* Check the response time of the request is acceptable.
* Check that response content header meet OWASP ASVS checklist

**Comment by vidhyamanojkumar** [comment]
@robert-clegg-tessella are there any upper and lower boundary limits for driver_cores (lower limit: 0.1?) and executor_cores (lower limit: 1?)?

**Comment by robert-clegg-tessella** [comment]
@vidhyamanojkumar these are set in the [web app configuration file](https://github.com/ukaea/piezo/blob/feature/submit-job-accepts-argument-input-as-array/%2345/piezo_web_app/PiezoWebApp/example_validation_rules.json). The deployment currently on OpenStack, which we run system tests against, has these permitted ranges:
* `driver_cores`: 0.1 - 1.0
* `executor_cores`: 1 - 4
