### ISSUE TITLE
Make get logs return 404 and fail when driver doesn't exist

### ISSUE THREAD

**Issue by oliver-tarrant-tessella** [ukaea/piezo#43]
When a driver pod doesn't exist get logs currently returns 
`{
    "status": "success",
    "data": "Kubernetes error when trying to get logs for driver \"driver-name\" in namespace \"default\": Not Found"
}`
Error message is fine but the status code should be 404 (not 200) and status should be fail

**Comment by robert-clegg-tessella** [comment]
System Test `Get Logs Of Non Job Returns Not Found Response` confirms this issue is now fixed
