### ISSUE TITLE
User can ask for status of job

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/piezo#46]
Status could be `Submitted`, `Running`, `Failed`, `Completed`

The route is `jobstatus`, e.g. URL `http://host-172-16-113-146.nubes.stfc.ac.uk:31924/jobstatus`

## Acceptance criteria
* After submitting a job, requesting its status returns a meaningful status (typically `Submitted` or `Running` immediately after submission, `Completed` or `Failed` long afterwards)
* Requesting the status of a job that does not exist returns a 404 not found response

## Test Scenarios
* Test all status feasible with a valid job. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase to see relevant status codes.
* Test that a 404 status and a user-friendly message is returned for a job that does not exist.
* Check the response time is acceptable when a bigger job is submitted (if anything like that is possible)
* Check that the response content header meets OWASP ASVS checklist.
* Test that a job that times out gives fails gracefully with a valid status code and response message.

**Comment by vidhyamanojkumar** [comment]
Status could be running, queuing, finished, **etc**? Could you specify all status options, please?
Is it possible to cancel the job?

**Comment by oliver-tarrant-tessella** [comment]
I've updated the issue to contain the statuses that I believe are possible although we are passing back the status directly from the spark operator and I can't find documentation that says exactly what these can be although I have never seen anything different. 

Jobs can be deleted once started which acts as cancelling them but upon deletion there is nothing to get a status from anymore

**Comment by robert-clegg-tessella** [comment]
The possible options for the status of a pod are given here: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase

**Comment by vidhyamanojkumar** [comment]
Thanks Oliver and Rob.
