### ISSUE TITLE
Add optional label input

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/piezo#52]
Labels may be added to k8s pods; these can be specified in the manifest sent to the Spark Operator.

One benefit of this is that all pods with a certain label can be deleted. This would be useful when cleaning up after system tests.

## Acceptance criteria
When submitting a job, the user has the option of including an input named "label" that has a string value.
Running the command `kubectl get pods -l userLabel=my_label` on a machine with `kubectl` configured should return only those pods for jobs with the label `my_label`.

## Test Scenarios
- [x] Test that labels can be defined for every pod available (all resource objects).
- [x] Test that label names cannot be duplicated NA
- [x] Test that label names are not case sensitive NA
- [x] Test that label names are not restricted by max character limit (check the max boundry 256 char? and min boundry 1 char? limit) 
- [x] Test if special characters are accepted in label names, specially :, /, white space

**Comment by oliver-tarrant-tessella** [comment]
Add details in wiki for adding label and arguments

**Comment by oliver-tarrant-tessella** [comment]
> Add details in wiki for adding label and arguments

Details added here: https://github.com/ukaea/piezo/wiki/WebAppUserGuide
