### ISSUE TITLE
Fix bug when deleting a job

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/piezo#58]
Requesting that a job be deleted caused a 500 Internal Server Error (regardless of whether the job existed or not). This was caused by a poorly-formatted body provided by the python kubernetes library.

The route is `deletejob`, e.g. URL `http://host-172-16-113-146.nubes.stfc.ac.uk:31924/deletejob`

## Acceptance criteria
* After submitting a job, requesting deletion results in a 200 Ok response. Subsequent attempts to delete or to get the status of the job result in a 404 Not Found response.

## Test Scenarios
* Test that a delete job returns a 200 status.
* Test that a delete job on job that doesn't exit gives a 404 status.
* Check the delete requests response time for a small job and a large job (if applies)
* Check that responses content header meet OWASPs ASVS checklist.

**Comment by vidhyamanojkumar** [comment]
Are there any user access restrictions? Can anyone delete a job?

**Comment by robert-clegg-tessella** [comment]
@vidhyamanojkumar There is currently no user auth in the system. This is not currently considered a priority, but we have designed the system so that implementing auth would be relatively straightforward in the future.
