### ISSUE TITLE
Web app rejects poorly-formatted job names

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/piezo#70]
Pod names must be composed of lower case characters, digits, `.` and `-`.  `.` and `-` must be surrounded by characters and/or digits.

The Kubernetes API will reject poorly-formatted names, but the error message it returns is not very clear. Instead, we should warn the user of this at the same time as all other validation warnings.

In addition see failed test cases from #51

## Acceptance criteria

Poorly-formatted job names are rejected by the web app, with a 400 response and helpful error message. Well-formatted job names are accepted as before.

The documentation in the [wiki user guide](https://github.com/ukaea/piezo/wiki/WebAppUserGuide#submit-a-job) matches the accepted formatting.

## Test Scenarios
- [x] Test that a job name follows the naming convention rules (no space, no special characters, no uppercase letter).
- [x] Test that the first character in the job name is an alphabet and not a number.
- [x] Test that a 400 status code and a user-friendly error message is displayed.

**Comment by vidhyamanojkumar** [comment]
@robert-clegg-tessella @oliver-tarrant-tessella Could we display the error message with the name restriction details, rather than adding a link to user guide?

**Comment by robert-clegg-tessella** [comment]
@vidhyamanojkumar I'd rather have these in just one place, rather than risk divergence. Having it on the wiki page means users can see what the restrictions are before submitting a job.
