### ISSUE TITLE
Catch key errors on getting job status

### ISSUE THREAD

**Issue by oliver-tarrant-tessella** [ukaea/piezo#79]
Bug fix to return "UNKNOWN" rather than 500 error when job status is not available. Solve by using catch key error on jobstatus as in getjobs. Solves issue when request is called too soon after submitting job.

# Acceptance criteria
`jobstatus` returns 200 response with message "UNKNOWN" when called very soon after the job is submitted. This bug occurs during system tests and when the kubernetes cluster is handling a large number of job submission at once.

## Test Scenario
- Test that 200 status with 'Unknown' message is returned when a request is sent very soon after the job is submitted.
- Test that 200 status with a valid message is returned when a request is sent for a completed job.

**Comment by robert-clegg-tessella** [comment]
Covered by system test `Status Of Job Immediately After Submission is Unknown`
